export const SLIDER_IMAGE_REQUEST = 'SLIDER_IMAGE_REQUEST'
export const SLIDER_IMAGE_SUCCESS = 'SLIDER_IMAGE_SUCCESS'
export const SLIDER_IMAGE_FAIL = 'SLIDER_IMAGE_FAIL'

export const ADVERTISMENT_IMAGE_REQUEST = 'ADVERTISMENT_IMAGE_REQUEST'
export const ADVERTISMENT_IMAGE_SUCCESS = 'ADVERTISMENT_IMAGE_SUCCESS'
export const ADVERTISMENT_IMAGE_FAIL = 'ADVERTISMENT_IMAGE_FAIL'
